const WS_MESSAGE_TYPE = {
  SEND_NAV_ID: 0,
  REQUEST_NAVIGATE: 1,
  SEND_PATH: 2,
  OFFER_REROUTE: 3,
  ACCEPT_REROUTE: 4,
  UPDATE_POSITION: 5,
  UPDATE_INSTRUCTION: 6,
  CANCEL_NAVIGATION: 7,
};

export default WS_MESSAGE_TYPE;